const offers = [
    {
      id: 1,
      title: 'Thirdebe Rock Point',
      location: 'Nova Scotia, Canada',
      type: 'Adventure',
      price: 599,
      image: 'https://i.ibb.co.com/8nSCBZZb/house.jpg',
      tags: ["Popular"],
    },
    {
      id: 2,
      title: 'Rare Lakefront Shipping',
      location: 'Nova Scotia, Canada',
      type: 'Relaxation',
      price: 599,
      image: 'https://i.ibb.co.com/8nSCBZZb/house.jpg',
      tags: ["Popular"],
    },
    {
      id: 3,
      title: 'Disney Springs',
      location: 'Nova Scotia, Canada',
      type: 'Culture',
      price: 599,
      image: 'https://i.ibb.co.com/8nSCBZZb/house.jpg',
      tags: ["Popular"],
    },
    {
        id: 4,
        title: 'Rare Lakefront Shipping',
        location: 'Nova Scotia, Canada',
        type: 'Relaxation',
        price: 599,
        image: 'https://i.ibb.co.com/8nSCBZZb/house.jpg',
        tags: ["Popular"],
      },
      {
        id: 5,
        title: 'Rare Lakefront Shipping',
        location: 'Nova Scotia, Canada',
        type: 'Relaxation',
        price: 599,
        image: 'https://i.ibb.co.com/8nSCBZZb/house.jpg',
        tags: ["Popular"],
      },
      {
        id: 6,
        title: 'Rare Lakefront Shipping',
        location: 'Nova Scotia, Canada',
        type: 'Relaxation',
        price: 599,
        image: 'https://i.ibb.co.com/8nSCBZZb/house.jpg',
        tags: ["Popular"],
      },
    // Add more dummy data as needed
  ];
  export default offers;